### ISSUE TITLE
misty should have a layman user mode

### ISSUE THREAD

**Issue by raghavan97** [riptideio/misty#1]
At this time, the way to use misty is to clone from github and then follow the instructions in the README.

It would be way cool , if we could do
pip install misty

> \<command to fetch a copy of config file\>

> bac_client --ini \<config-file\>

By doing this a layman who is not necessarily a python programmer can use the bac_client

**Comment by raghavan97** [comment]
Merged to master

**Comment by kushan-26** [comment]
I tried using pip install but I got an error when I ran "cp_ini -t client ./bc.ini"
Error:
Traceback (most recent call last):
  File "/home/pi/miniconda3/bin/cp_ini", line 46, in <module>
    main()
  File "/home/pi/miniconda3/bin/cp_ini", line 37, in main
    shutil.copy(ini_file, dest)
  File "/home/pi/miniconda3/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/pi/miniconda3/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/miniconda3/cfg/bac_client.ini'

Any reason I'm getting this?

**Comment by raghavan97** [comment]
Please try installing in python 2.7 environment.
This package has not yet been migrated to py3.

Raghavan V
