### ISSUE TITLE
RS485 Half DUPLEX not working

### ISSUE THREAD

**Issue by adelvalle62** [riptideio/misty#12]
Hello Raghavan;

I've got issues because the Transmition and Reception over RS485 half duplex seems not working good because the MSTP devices get no response but I am thinking that could be a problem at low level. To ensure that everything works I test the solution as well using the BACNET explorer YABE that works perfectly in the environment over LINUX and WINDOWS

I just need to be sure that your package works OK with half duplex, the RS485 interface is ttyUSB0 and we tested on a raspberry CPU as well with ttsySC0 both with the same results

After loaded the packages with dependencies I tried with: 

$ export PYTHONPATH=$PWD
$ python3.8 misty/samples/bac_client.py --ini misty/samples/bac_client.ini

The execution was OK, but when I try any function as whois iam, read or write I always receive a no response

Regards and thank you in advance

**Comment by adelvalle62** [comment]
Hello Raghavan;
It was my fault a bad ini file now everything works fine

Congratulations for your misty MSTP package
Regards and thanks

**Comment by codev123** [comment]
> Hello Raghavan; It was my fault a bad ini file now everything works fine
> 
> Congratulations for your misty MSTP package Regards and thanks

can you please tell me what was issue with your ini file, i am facing exactly same issue. able to execute firmware but not getting any response from connected mstp device on commands whois iam read etc
