### ISSUE TITLE
RS485 Interface on Raspberry Pi is not initialized.

### ISSUE THREAD

**Issue by sansal54** [riptideio/misty#2]
I have a working RS485 shield mounted on my Raspberry Pi device. And I use it successfully for modbus rtu communication. So I am pretty sure that my linux device and RS485 interface is ok. I tried to use misty for bacnet mstp communication. But I was not able to start bacnet client. I followed all procedures to set it up. When I try to run code with ini file , I get :

```
Initialized the socket
mac_address = 25 
max master = 127
baud rate = 76800 
max info frames = 1 
/: Is a directory
RS485: Initializing /
```
and it stops here. And my .ini file is :

```
[BACpypes]
objectName: BACClient
; MSTP Local address
address: 25
; The serial port device
interface: /dev/ttySC0
; other mstp config parameters max_masters, baudrate, maxinfo
max_masters: 127
baudrate: 76800
maxinfo: 1
objectIdentifier: 599
maxApduLengthAccepted: 1024
segmentationSupported: segmentedBoth
vendorIdentifier: 15
foreignPort: 0
foreignBBMD: 128.253.109.254
foreignTTL: 30
```
So I need a help here.

**Comment by raghavan97** [comment]
The message "RS485: Initializing /" indicates that the interface is not passed to it correctly. Can you double check if the correct .ini file is being passed to the bacnet client ?

Also as a normal user you might not have access to the device read and write. Please try using "sudo" when you invoke the bacnet client.

Unfortunately I dont have a Raspberry Pi to test it. Sorry about that.

**Comment by raghavan97** [comment]
@sansal54 ,

Can you please check on the latest release ?

I understand that the issue was caused was due to lack of py3 support.
Now we have the support for py3.
It should now work for you correctly.

**Comment by sansal54** [comment]
Thanks. Indeed, it worked. But this time ;I get another issue. My MSTP device is working and I can discover everything about it easily on Windows. But here I cant discover anything about it even if everthing is configured properly. It even doesnt respond to whois. Here is my python code and the output :+1: 

```
import subprocess

command = "bc --ini ./bc.ini"  # the shell command
process = subprocess.Popen(command.split(), stdin=subprocess.PIPE, stdout=subprocess.PIPE, shell=False)

process.stdin.write(b"whois")

process_output = process.communicate()[0]
process_error = process.communicate()[1]

process.stdin.close()

print(process_output.split(b'\n'))
print(process_error)
```

sansal@sansal-xubuntu:~/workspace/mstp_test$ sudo pipenv run python3 main.py
Initialized the socket
mac_address = 25 
max master = 127 
baud rate = 9600 
max info frames = 1 
MS/TP MAC: 19
MS/TP Max_Master: 7F
MS/TP Max_Info_Frames: 1
mstp_path=/var/tmp/ma_88udec2i/mstpttyUSB0 
[b'RS485: Initializing /dev/ttyUSB0=success!', b'Cleaned up MSTP temp directory', b'']
None

**Comment by sansal54** [comment]
thanks, this time it worked.
