### ISSUE TITLE
Simulate MS/TP Device using misty and bacpypes

### ISSUE THREAD

**Issue by memanasraza** [riptideio/misty#3]
Hi! I have simulated BACnet/IP devices in windows using BACpypes and these are detected in YABE Explorer. Want to simulate BACnet MS/TP devices on WINDOWS using misty.
But not able to do so.

How can I set up my code and _~ini files_ for Windows?

Thanks,
Anas

**Comment by raghavan97** [comment]
Anas,

misty works only on Linux platform.
It does not support Windows.

Thanks.

Bye,
Raghavan V

**Comment by memanasraza** [comment]
Now I am running it on the Linux platform. Created serial ports. Changed the Queue module import for Python 3.8.
I am getting this error:
OSError: /home/../.../misty/misty/mstplib/libmstp_agent.so: cannot open shared object file: No such file or directory

**Comment by raghavan97** [comment]
Can you try with a 2.7 virtual env ?
That file should be present.

**Comment by raghavan97** [comment]
I tried installing misty on a py3 virt env and I dont see the libmstp_agent.so (since it is not ported to py3)
I do see the file in py2.7 env.

(py3port) root@513d426a74d4:/# find ~/.virtualenvs/py2port/ -name 'libmstp*.so'
/root/.virtualenvs/py2port/lib/python2.7/site-packages/misty/mstplib/libmstp_agent.so

**Comment by raghavan97** [comment]
Did it work for you Anas ?

Please let me know. 
I am hoping to raise a Issue for support of Python 3 and can take care of the port.

**Comment by memanasraza** [comment]
Thank you for helping @raghavan97 I followed the make_file step in the documentation. a file libmstp_agent.so was created in my cloned repository.
Sometimes I get the issue of _bind failed_. It comes without any regular Python exception details.
How can I fix that?

**Comment by raghavan97** [comment]
Bind fails , if you have an instance of bacnet client already running. The new instance tries to bind again to the same port and it fails. Make sure you exit from the old bacnet client instance before you start the new one. That should solve the problem.

Thanks.

**Comment by memanasraza** [comment]
I don't have any other bacnet client running..

**Comment by memanasraza** [comment]
It's working on Python 2.7. 
Thank you @raghavan97 .

**Comment by raghavan97** [comment]
misty 0.0.9 is supported on python 2.7 only

**Comment by memanasraza** [comment]
The new version is working on Python 3. 
Thank you @raghavan97.

Anas.
