### ISSUE TITLE
Port misty to work on python3

### ISSUE THREAD

**Issue by raghavan97** [riptideio/misty#4]

**Comment by JoelBender** [comment]
This effort will be synced up with **bacpypes3** which is under construction.

**Comment by raghavan97** [comment]
@JoelBender ,

Thanks a lot. That would be wonderful to be part of bacpypes3.

I just made this package compatible with py2/py3.

Thanks.
Raghavan V

**Comment by ChristianTremblay** [comment]
Glad to hear that....py27 was a no go for me....but I guess I don't have any excuses :)
